# Generated by Django 3.1.6 on 2021-02-06 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('vendor', models.CharField(max_length=60)),
                ('category', models.CharField(choices=[('Grocery', 'Grocery'), ('Education', 'Education'), ('Transport', 'Transport'), ('Vacation', 'Vacation'), ('Dining-out', 'Dining Out'), ('Insurance', 'Insurance'), ('Utilities', 'Utilities')], default='Grocery', max_length=15)),
            ],
        ),
    ]
